name: 'dbt_agr'
version: '1.0.0'
config-version: 2

profile: 'dbt_postgress'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_agr:
    local:
      directory: 'models'




