{{ config(materialized='view') }}

SELECT
    cl.applicationuid,
    cl.rep_type,
    cl.second_name,
    cl.first_name,
    cl.third_name,
    cl.birth_dt,
    cl.applicantid,
    cl.name_id,
    cl.report_id,
    cl.report_dt,
    cl.loan_id,
    cl.class_type,
    cl.is_bank,
    cl.date_start,
    cl.date_end_plan,
    cl.date_end_fact,
    cl.credit_amount,
    cl.current_debt_rur,
    cl.delinquent_debt_rur,
    cl.product,
    cl.currency,
    cl.interest_rate_month,
    cl.is_debtor,
    cl.is_guarantor,
    cl.pmtstring84m,
    cl.pmtstringstart,
    cl.infconfirmdate,
    cl.currentdelq,
    cl.inquiry1week,
    cl.inquiry1month,
    cl.inquiry3month,
    cl.inquiry6month,
    cl.next_pmt,
    cl.business_category,
    cl.status,
    cl.relationship,
    cl.type_,
    cl.uuid,
    cl.collateralcode,
    cl.next_pmt AS month_pmt,
    SUBSTRING(CAST(NOW() AS VARCHAR), 1, 19) AS t_changed_dttm
FROM {{ ref('nvg_data_gr_loans_np') }}  AS cl