{{ config(materialized='view') }}

SELECT
    a.applicationuid,
    a.application_date,
    a.applicantid,
    a.report_dt,
    a.loan_id,
    a.class_type,
    a.is_bank,
    a.date_start,
    a.date_end_plan,
    a.date_end_fact,
    a.credit_amount,
    a.card_limit,
    a.current_debt_rur,
    a.next_pmt,
    a.delinquent_debt_rur,
    a.product,
    a.is_diff,
    a.is_individual_pp,
    a.currency,
    a.interest_rate_month,
    a.is_debtor,
    a.is_guarantor,
    a.credit_amount_rur,
    a.card_limit_rur,
    a.credit_amount_rur_0,
    a.card_limit_rur_0,
    a.credit_amount_rur_b,
    a.card_limit_rur_b,
    a.remain_term,
    a.is_ik,
    a.is_pk,
    a.is_ak,
    a.is_kk,
    a.is_mk,
    a.is_ok,
    a.is_advanced,
    a.is_advanced_25,
    a.prev_date_end_fact__bank,
    a.prev_date_end_fact,
    a.is_open,
    a.for_length__date_start__bank,
    a.for_length__date_start,
    a.for_length__date_end_fact,
    -- обязательство рассчитывается только по заёмщикам/созаёмщикам и поручителям; в остальных случаях - 0
    a.liability_rur,
    a.liability_rur_rkk,
    -- Для определения не карт, среди открытых/закрытых, по дате открытия
    a.start_desc_num,
    a.start_asc_num,
    -- Для определения не карт, среди открытых/закрытых, по дате закрытия
    a.end_desc_num,
    -- Для определения ПК среди всех (открытых, закрытых)
    a.start_pk_desc_num,
    a.start_pk_asc_num,
    row_number() OVER (PARTITION BY a.applicationuid, a.applicantid, a.application_date, a.is_debtor, a.is_open, a.is_pk, a.is_bank ORDER BY a.liability_rur_rkk DESC NULLS LAST, ABS(loan_id) DESC) AS liab_pk_desc_num,
    row_number() OVER (PARTITION BY a.applicationuid, a.applicantid, a.application_date, a.is_debtor, a.is_open, a.is_ik, a.is_bank ORDER BY a.liability_rur_rkk DESC NULLS LAST, ABS(loan_id) DESC) AS liab_ik_desc_num,
    row_number() OVER (PARTITION BY a.applicationuid, a.applicantid, a.application_date, a.is_debtor, a.is_open, a.is_kk, a.is_bank ORDER BY a.liability_rur_rkk DESC NULLS LAST, ABS(loan_id) DESC) AS liab_kk_desc_num,
    row_number() OVER (PARTITION BY a.applicationuid, a.applicantid, a.application_date, a.is_debtor, a.is_open, a.is_ak, a.is_bank ORDER BY a.liability_rur_rkk DESC NULLS LAST, ABS(loan_id) DESC) AS liab_ak_desc_num
FROM {{ ref('nvg_data_gr_bki_t3') }}  a