{{ config(materialized='view') }}

SELECT
    applicationuid,
    sct.application_date,
    rep_type,
    second_name,
    first_name,
    third_name,
    birth_dt,
    applicantid,
    CAST(name_id AS DECIMAL(19,0)) AS name_id,
    CONCAT(rep_type, '_', CAST(report_id AS VARCHAR)) AS report_id,
    report_dt,
    CAST(loan_id AS DECIMAL(19,0)) AS loan_id,
    class_type,
    CAST(is_bank AS INTEGER) AS is_bank,
    date_start,
    date_end_plan,
    date_end_fact,
    CAST(credit_amount AS DECIMAL(19,2)) AS credit_amount,
    CAST(current_debt_rur AS DECIMAL(19,2)) AS current_debt_rur,
    CAST(delinquent_debt_rur AS DECIMAL(19,2)) AS delinquent_debt_rur,
    product,
    currency,
    CAST(interest_rate_month AS DECIMAL(38,6)) AS interest_rate_month,
    is_debtor,
    is_guarantor,
    pmtstring84m,
    pmtstringstart,
    infconfirmdate,
    currentdelq,
    CAST(inquiry1week AS DECIMAL(10,0)) AS inquiry1week,
    CAST(inquiry1month AS DECIMAL(10,0)) AS inquiry1month,
    CAST(inquiry3month AS DECIMAL(10,0)) AS inquiry3month,
    CAST(inquiry6month AS DECIMAL(10,0)) AS inquiry6month,
    CAST(next_pmt AS DECIMAL(19,2)) AS next_pmt,
    CAST(business_category AS DECIMAL(15,0)) AS business_category,
    status,
    relationship,
    type_,
    CAST(month_pmt AS DECIMAL(38,6)) AS month_pmt,
    uuid,
    NULL AS worstpmtpat,
    NULL AS nextpmt,
    collateralcode,
    NOW() AS t_changed_dttm,
    CAST(0 AS SMALLINT) AS t_deleted_flg,
    NULL AS t_process_task_id,
    CAST(1 AS SMALLINT) AS t_active_flg
FROM  {{ ref('nvg_data_gr_month_pmt') }}
CROSS JOIN {{ ref('nvg_cre_date') }} AS sct